In [61]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [63]:
df=pd.read_csv(r"C:/Users/veerp/OneDrive/Certificate/Data set/hiring.csv")

In [65]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [67]:
df["test_score(out of 10)"]=df["test_score(out of 10)"].fillna(df["test_score(out of 10)"].mean())

In [69]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN               8.000000                           9      50000
1        NaN               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [71]:
print(df[df["experience"].isnull()])

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000

In [73]:
df["experience"] = df["experience"].fillna(3)  # fill all NaN with 3 years

In [75]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          3               8.000000                           9      50000
1          3               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [81]:
# actually we are replacing value string to int
df.loc[3, "experience"] = 2   # manually fill with 2 years
df.loc[7, "experience"] = 5   # manually fill with 5 years
df.loc[2, "experience"] = 5
df.loc[4, "experience"] = 7
df.loc[5, "experience"] = 3
df.loc[6, "experience"] = 10

In [83]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          3               8.000000                           9      50000
1          3               8.000000                           6      45000
2          5               6.000000                           7      60000
3          2              10.000000                          10      65000
4          7               9.000000                           6      70000
5          3               7.000000                          10      62000
6         10               7.857143                           7      72000
7          5               7.000000                           8      80000

In [87]:
x=df[["experience","test_score(out of 10)","interview_score(out of 10)"]]
y=df[["salary($)"]]

In [89]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [91]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [93]:
predection=model.predict(x_test)
print(predection)

[[101196.02169982]
 [ 63265.82278481]]

In [95]:
predicted = model.predict([[2, 9, 6]])
print(predicted[0][0])

36881.01265822786

C:\Users\veerp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [101]:
predicted = model.predict([[12, 10, 10]])
print(predicted[0][0])

133475.94936708856

C:\Users\veerp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [103]:
score=model.score(x_test,y_test)
print(score)

-10.987128910529105