In [30]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
df = pd.read_csv("C:/Users/veerp/OneDrive/Desktop/ml/homeprices.csv")
print(df.head())

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [32]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [35]:
y = df[['price']] 
x = df[['area']]

In [36]:
x

   area
0  2600
1  3000
2  3200
3  3600
4  4000

In [39]:
y

    price
0  550000
1  565000
2  610000
3  680000
4  725000

In [42]:
type(x)

pandas.core.frame.DataFrame

In [44]:
print(df['area'].dtype)

int64

In [46]:
print(df['price'].dtype)

int64

In [48]:
model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [50]:
predictions = model.predict([[3300]])
print("Predictions:", predictions[0])

Predictions: [628715.75342466]

C:\Users\veerp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [52]:
df = pd.read_csv("C:/Users/veerp/OneDrive/Desktop/ml/areas.csv")

In [54]:
df

    area
0   1000
1   1500
2   2300
3   3540
4   4120
5   4560
6   5490
7   3460
8   4750
9   2300
10  9000
11  8600
12  7100

In [56]:
print(z)
print(type(z))

[['area']]
<class 'list'>

In [58]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   area    13 non-null     int64
dtypes: int64(1)
memory usage: 236.0 bytes

In [65]:
z=[["area"]]

In [67]:
predictions = model.predict(z)

C:\Users\veerp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.

In [69]:
predictions[:13]

array([[628715.75342466]])