In [5]:
#Pandas Data Structures
#Series (1D labeled array)
import pandas as pd

s = pd.Series([10, 20, 30, 40], index=['a','b','c','d'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [7]:
#DataFrame (2D table)
data = {
    'Name': ['Amit', 'Neha', 'Raj'],
    'Age': [22, 25, 28],
    'City': ['Delhi', 'Mumbai', 'Chennai']
}
df = pd.DataFrame(data)
print(df)

   Name  Age     City
0  Amit   22    Delhi
1  Neha   25   Mumbai
2   Raj   28  Chennai

In [9]:
s=pd.Series(range(5))
print(s)

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [13]:
S = pd.Series(range(1,10,2))
print(S)

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [15]:
S = pd.Series(range(1,10))
print(S)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [17]:
import sys
print(sys.executable)

C:\Users\veerp\anaconda3\python.exe

In [19]:
import pandas as pd 
import numpy as np

In [23]:
df = pd.read_csv("C:/Users/veerp/OneDrive/Certificate/Data set/student_results.xls")

In [25]:
print(df)

   Student ID  Class  Study hrs  Sleeping hrs  Social Media usage hrs  \
0        1001     10          2             9                       3
1        1002     10          6             8                       2
2        1003     10          3             8                       2
3        1004     11          0            10                       1
4        1005     11          4             7                       2
5        1006     11         10             7                       0
6        1007     12          4             6                       0
7        1008     12         10             6                       2
8        1009     12          2             8                       2
9        1010     12          6             9                       1

   Mobile Games hrs  Percantege
0                 5          50
1                 0          80
2                 4          60
3                 5          45
4                 0          75
5                 0          96
6                 0          80
7                 0          90
8                 4          60
9                 0          85

In [59]:
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [31]:
df.sample(3)          # random 3 rows

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
6,1007,12,4,6,0,0,80
1,1002,10,6,8,2,0,80
4,1005,11,4,7,2,0,75

In [33]:
df.value_counts()

Student ID  Class  Study hrs  Sleeping hrs  Social Media usage hrs  Mobile Games hrs  Percantege
1001        10     2          9             3                       5                 50            1
1002        10     6          8             2                       0                 80            1
1003        10     3          8             2                       4                 60            1
1004        11     0          10            1                       5                 45            1
1005        11     4          7             2                       0                 75            1
1006        11     10         7             0                       0                 96            1
1007        12     4          6             0                       0                 80            1
1008        12     10         6             2                       0                 90            1
1009        12     2          8             2                       4                 60            1
1010        12     6          9             1                       0                 85            1
Name: count, dtype: int64

In [39]:
df.apply(len)

Student ID                10
Class                     10
Study hrs                 10
Sleeping hrs              10
Social Media usage hrs    10
Mobile Games hrs          10
Percantege                10
dtype: int64

In [41]:
df.to_csv("output.csv", index=False)

In [43]:
df.head()        # first 5 rows

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75

In [45]:
df.tail()        # last 5 rows

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [47]:
df.shape         # rows, columns

(10, 7)

In [49]:
df.info()        # summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Student ID              10 non-null     int64
 1   Class                   10 non-null     int64
 2   Study hrs               10 non-null     int64
 3   Sleeping hrs            10 non-null     int64
 4   Social Media usage hrs  10 non-null     int64
 5   Mobile Games hrs        10 non-null     int64
 6   Percantege              10 non-null     int64
dtypes: int64(7)
memory usage: 692.0 bytes

In [53]:
df.describe()    # statistics

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
count,10.00000,10.000000,10.000,10.000000,10.000000,10.000000,10.000000
mean,1005.50000,11.100000,4.700,7.800000,1.500000,1.800000,72.100000
std,3.02765,0.875595,3.335,1.316561,0.971825,2.347576,17.342626
min,1001.00000,10.000000,0.000,6.000000,0.000000,0.000000,45.000000
25%,1003.25000,10.250000,2.250,7.000000,1.000000,0.000000,60.000000
50%,1005.50000,11.000000,4.000,8.000000,2.000000,0.000000,77.500000
75%,1007.75000,12.000000,6.000,8.750000,2.000000,4.000000,83.750000
max,1010.00000,12.000000,10.000,10.000000,3.000000,5.000000,96.000000

In [55]:
df.columns       # column names

Index(['Student ID', 'Class', 'Study hrs', 'Sleeping hrs',
       'Social Media usage hrs', 'Mobile Games hrs', 'Percantege'],
      dtype='object')

In [57]:
df.dtypes        # datatypes

Student ID                int64
Class                     int64
Study hrs                 int64
Sleeping hrs              int64
Social Media usage hrs    int64
Mobile Games hrs          int64
Percantege                int64
dtype: object

In [61]:
df.head()        # first 5 rows

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75